name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v1.0.0'

jobs:
  build-installer:
    uses: ./.github/workflows/build-installer.yml
    with:
      configuration: 'Release'
    secrets:
      VSTO_CERTIFICATE: ${{ secrets.VSTO_CERTIFICATE }}
      VSTO_CERT_THUMBPRINT: ${{ secrets.VSTO_CERT_THUMBPRINT }}
      VSTO_CERT_PASSWORD: ${{ secrets.VSTO_CERT_PASSWORD }}

  create-release:
    needs: build-installer
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download installer
        uses: actions/download-artifact@v4
        with:
          name: installer-Release
          path: dist/

      - name: Setup certificate files
        shell: bash
        env:
          VSTO_CERTIFICATE: ${{ secrets.VSTO_CERTIFICATE }}
        run: |
          mkdir -p packages
          
          # 导出公钥证书
          if [ -n "$VSTO_CERTIFICATE" ]; then
            echo "$VSTO_CERTIFICATE" | base64 -d > temp.pfx
            openssl pkcs12 -in temp.pfx -nokeys -out packages/PPMeta-Certificate.cer -password pass:"${{ secrets.VSTO_CERT_PASSWORD }}" || true
            rm -f temp.pfx
          fi
          
          # 创建安装指南
          cat > packages/INSTALL_GUIDE.md << 'EOF'
          # PPMeta 安装指南
          
          ## MSI 安装程序
          1. 双击 PPSetup.msi 安装程序
          2. 按照向导完成安装
          
          ## 证书安装（如需要）
          如果遇到安全警告，请安装提供的证书：
          1. 双击 PPMeta-Certificate.cer
          2. 点击"安装证书"
          3. 选择"受信任的发布者"存储
          
          ## VSTO 运行时
          PowerPoint 加载项需要 VSTO 运行时支持，如未安装请访问：
          https://www.microsoft.com/download/details.aspx?id=48217
          EOF

      - name: Create release packages
        run: |
          cd packages
          cp ../dist/*.msi ./ 2>/dev/null || echo "No MSI files found"
          
          # MSI 包
          zip -r ../ppmeta-msi-${{ github.ref_name }}.zip . || true
          
          # VSTO 包
          cd ..
          mkdir -p vsto-package
          echo "VSTO 文件包含在 MSI 安装程序中" > vsto-package/README.txt
          cp packages/*.cer vsto-package/ 2>/dev/null || true
          cp packages/INSTALL_GUIDE.md vsto-package/ || true
          zip -r ppmeta-vsto-${{ github.ref_name }}.zip vsto-package/ || true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ppmeta-msi-${{ github.ref_name }}.zip
            ppmeta-vsto-${{ github.ref_name }}.zip
          body: |
            ## PPMeta ${{ github.ref_name }} 发布
            
            ### 下载说明
            - **ppmeta-msi-${{ github.ref_name }}.zip**: MSI安装程序包 + 证书 + 安装指南
            - **ppmeta-vsto-${{ github.ref_name }}.zip**: VSTO程序包 + 证书 + 安装指南
            
            ### 安装步骤
            1. 下载对应的安装包
            2. 解压缩文件
            3. 阅读 INSTALL_GUIDE.md 安装指南
            4. 如需要，先安装证书再安装程序
            
            ### 系统要求
            - Windows 10/11
            - Microsoft PowerPoint 2016 或更高版本
            - .NET Framework 4.8
            - Visual Studio Tools for Office Runtime
          prerelease: false
          draft: false
